& .\Speech.ps1
Invoke-CharacterTTS MyNarrator "The next morning, ClaireWilson brought the file filled with proposals that she had prepared overnight and went to the Emgrand Group office with CharlieWade. Standing in front of the 100-story building, she suddenly felt as if her heart was hollow and empty. How could such a magnificent company like Emgrand collaborate with the Wilson family? Not to mention that they were aiming for a thirty-million-dollar deal. It was like a beggar approaching a wealthy man and asking for a thirty-million-dollar change. It was absolutely ridiculous. However, she had promised her grandmother and accepted the challenge in front of everyone, so she had to go for it no matter what..."
Invoke-CharacterTTS CharlieWade "Dear, don't worry, go ahead, you'll make it. Trust me."
Invoke-CharacterTTS ClaireWilson "Alright, let's hope so! Wait for me here."
Invoke-CharacterTTS MyNarrator "She took a deep breath and walked through the door. As she entered, CharlieWade took out his phone and called DorisYoung."
Invoke-CharacterTTS CharlieWade "Miss Young, my wife is going up to see you as we speak. You should know what to do!"
Invoke-CharacterTTS DorisYoung "Yes, Mr. Wade. Don't worry, I'll fulfill your every request."
Invoke-CharacterTTS CharlieWade "By the way, I heard that Emgrand Group has a rather close connection with the Jones family. Is that true?"
Invoke-CharacterTTS DorisYoung "Yes, we did have a lot of projects with them, completed and ongoing. They wish to collaborate with us again on this new megaproject and they've submitted the proposals and materials for my review. However, it is up to you to decide, Mr. Wade."
Invoke-CharacterTTS CharlieWade "I don't want the Jones family to be involved in the new project and any other projects in the future."
Invoke-CharacterTTS DorisYoung "Yes, sure. Don't worry, I'll do as you say!"
Invoke-CharacterTTS MyNarrator "Meanwhile, ClaireWilson walked into Emgrand Group's office building and waited for her appointment at the front desk. Not long after, a graceful female assistant approached her and asked, 'Hi, are you Miss Claire Wilson? Miss Young is waiting for you in her office, please follow me.' ClaireWilson nodded in a trance and was escorted directly to DorisYoung's office."
Invoke-CharacterTTS DorisYoung "Hi, Miss Wilson, I'm Doris Young, vice chairman of Emgrand Group—nice meeting you."
Invoke-CharacterTTS ClaireWilson "Hello, Miss Young, thank you for seeing me. I'm here to talk to you about the hotel project. Although Wilson Group is not as strong and prominent as other companies, I can assure you that we work very hard and have established a very positive reputation in the interior design and decoration industry."
Invoke-CharacterTTS DorisYoung "I've seen your documents; I think you are the perfect partner for us."
Invoke-CharacterTTS ClaireWilson "Really? Is it true?"
Invoke-CharacterTTS DorisYoung "Of course. I admit that Wilson Group does not match our requirements and qualifications, but our chairman thinks highly of you and is willing to give it a chance."
Invoke-CharacterTTS ClaireWilson "May I know who your chairman is?"
Invoke-CharacterTTS DorisYoung "Our chairman is Mr. Wade from Eastcliff."
Invoke-CharacterTTS ClaireWilson "Mr. Wade? I don't think I know anyone by the last name of Wade except for my husband."
Invoke-CharacterTTS DorisYoung "Miss Wilson, I see in your proposal that your quotation for the agreement is thirty million dollars?"
Invoke-CharacterTTS ClaireWilson "Is it too much?"
Invoke-CharacterTTS DorisYoung "Oh no, it is actually less than what we have budgeted for."
Invoke-CharacterTTS ClaireWilson "What do you mean?"
Invoke-CharacterTTS DorisYoung "Our chairman told me to increase the quotation to sixty million dollars."
Invoke-CharacterTTS DorisYoung "Look, we've drafted the contract in advance for a total of sixty million dollars. If you have no problem with it, we can sign the contract now."
Invoke-CharacterTTS ClaireWilson "Huh? This..."
Invoke-CharacterTTS MyNarrator "ClaireWilson gaped, dumbfounded. She had never expected that Emgrand Group would prepare the contract beforehand, let alone double the amount. Suddenly, she recalled CharlieWade's serious and earnest face when he had asked her to accept the task at the family meeting. Why was he so confident? When they stood at Emgrand Group's entrance she had been doubtful and pessimistic, but he had seemed so positive and undaunted. Could it be that he had known the outcome all along? Who was he..."