Invoke-CharacterTTS Narrator 'Chapter 9'
Invoke-CharacterTTS Narrator "For an instant, an abrupt and outlandish thought appeared in Claire's mind. The Mr. Wade that Doris mentioned, could he really be her husband, Charlie Wade? When she processed it again, she found it to be too preposterous. How could it be! Charlie was an orphan who grew up in a welfare home! However, who else in the world would treat her so well besides Charlie? Thirty million dollars was an extravagant hope, but they gave her sixty million… She couldn't help but asked curiously,"
Invoke-CharacterTTS ClaireWilson "Miss Young, may I know if your chairman is Charlie Wade?"
Invoke-CharacterTTS Narrator "Doris's heart skipped a beat. The boss had already demanded her to keep his identity secret, only to reveal his last name to the public. She would be blamed if his wife guessed it! She shook her hands frantically and said,"
Invoke-CharacterTTS DorisYoung "Miss Wilson, I hope you can drop it. Our chairman is the descendant of a prominent family in Eastcliff. His identity is highly confidential and I have no right to disclose it."
Invoke-CharacterTTS Narrator "Claire nodded gently. She composed herself upon the mention of the descendant in Eastcliff. Charlie was an orphan, he was definitely not a so-called descendant from a prominent family. Indeed, she was overthinking it. Claire still felt a little dizzy and confused when she exited Doris's office. She was holding a sixty million dollar contract between Wilson Group and Emgrand Group in her hand. Everything unfolded like a dream. As soon as she saw Charlie at the entrance, she rushed to him excitedly and said,"
Invoke-CharacterTTS ClaireWilson "Charlie, I did it! I did it!"
Invoke-CharacterTTS Narrator "Charlie grinned in his heart and thought, 'Your husband is the owner of Emgrand Group, of course you'd get the deal.' However, he pretended to be surprised and said,"
Invoke-CharacterTTS CharlieWade "Wow! You managed to strike the deal for such a tough project! Dear, you're so incredible!"
Invoke-CharacterTTS ClaireWilson "Not really, it's not that I'm good at it, but it seems that they had given the project to me for free."
Invoke-CharacterTTS CharlieWade "Huh?" 
Invoke-CharacterTTS Narrator "Charlie donned a confused look."
Invoke-CharacterTTS CharlieWade "Why do you say that?"
Invoke-CharacterTTS Narrator "Claire was afraid that Charlie would be jealous if she told him about the chairman's intention, so she quickly diverted his attention and said,"
Invoke-CharacterTTS ClaireWilson "It's a long story. Let's go back to the office now and tell everyone the good news!"
Invoke-CharacterTTS Narrator "Charlie laughed."
Invoke-CharacterTTS CharlieWade "Okay! This Time, that bastard Harold must honor the bet and kneel before me!"
Invoke-CharacterTTS Narrator "Claire nodded."
Invoke-CharacterTTS ClaireWilson "Yes! He is always so snobbish and arrogant, let's give him a taste of his own medicine!"
Invoke-CharacterTTS Narrator "Truth be told, Claire had her own temperament too. Harold And the rest of the family members had always looked down upon her and her husband, but now that she struck the impossible deal, she intended to tame them to be a little bit more humble. Ten minutes later, they arrived at Wilson Group. Everyone was sitting in the conference room, looking strange and peculiar. They knew that Claire had gone to Emgrand Group early in the morning, but no one believed that she could make it, they were here to make fun of her. Unexpectedly, she came back way earlier than they anticipated. When Claire and Charlie entered the conference room, everyone was looking at them with a sneering and sarcastic look. Harold started ignorantly," 
Invoke-CharacterTTS HaroldWilson "Hey, Claire, you've come back in half an hour, huh? You couldn't even get through their door, am I right? Hahaha!" 
Invoke-CharacterTTS Narrator "Wendy continued,"
Invoke-CharacterTTS WendyWilson "Claire, you've failed in less than an hour. Breaking a world record, I see!"
Invoke-CharacterTTS Narrator "A gloomy cloud hovered over Lady Wilson's face. She was annoyed. She knew that the project and Emgrand Group were difficult to tackle, but Claire should at least be serious and determined even if she failed! How could she give up so easily? Lady Wilson glared at her and growled,"
Invoke-CharacterTTS LadyWilson "Claire Wilson, you disappoint me."
Invoke-CharacterTTS Narrator "Charlie frowned at their reactions. Could they be more disgusting than this? They were ridiculing and chiding Claire without knowing the results yet! Especially Harold Wilson, the cocky bastard! Who did he think he was? How could he be so pompous? He should be getting ready to kneel before him! Claire was initially very excited and thrilled, but facing the crowd's mocking and teasing, the wrath of fury was burning inside her. She furrowed and said,"
Invoke-CharacterTTS ClaireWilson "I'm sorry to let you down, but I've struck a deal with Doris Young of Emgrand Group!"
Invoke-CharacterTTS LadyWilson "What? You did it?"
Invoke-CharacterTTS WendyWilson "No! No way! Impossible! You couldn't even meet Doris Young!"
Invoke-CharacterTTS Narrator "Everyone recoiled in shock."
Invoke-CharacterTTS WendyWilson "Claire Wilson, do you think we'll buy it?"
Invoke-CharacterTTS Narrator "Harold regained his composure, slapped the table and said furiously,"
Invoke-CharacterTTS HaroldWilson "Miss Young of Emgrand Group is a renowned elite in the city, why would she want to meet you? Are you not clear about who you are?"
Invoke-CharacterTTS Narrator "Facing everyone's doubts and accusations, Claire retrieved the contract and handed it to Lady Wilson."
Invoke-CharacterTTS ClaireWilson "This is the contract. Please take a look at it."
Invoke-CharacterTTS Narrator "The contract was like a bomb that exploded in the middle of the conference room, sending shock waves across everyone in the room! Harold still refused to believe it, he shouted loudly,"
Invoke-CharacterTTS HaroldWilson "She must have forged the document! I don't believe that she can handle Emgrand Group!"
Invoke-CharacterTTS WendyWilson "He's right!" 
Invoke-CharacterTTS Narrator "Wendy added in great dismay."
Invoke-CharacterTTS WendyWilson "Who does she think she is to strike a deal with Emgrand? It is a thirty million dollar project! If she can do it, I would've already gotten the deal a long time ago!"
Invoke-CharacterTTS Narrator "Claire sneered."
Invoke-CharacterTTS ClaireWilson "My cousin, you're wrong, it's not thirty million dollars, it's sixty million!"
Invoke-CharacterTTS WendyWilson "No way!" 
Invoke-CharacterTTS Narrator "Wendy grinned." 
Invoke-CharacterTTS WendyWilson "Sixty million dollars contract? You find it funny to lie like that, don't you? You think we're all fools, don't you? If you say the deal is sixty million, I can tell everyone that I'd get a hundred million dollar contract!"
Invoke-CharacterTTS Narrator "Harold curled his lips in disdain and said,"
Invoke-CharacterTTS HaroldWilson "Claire, you're treating Grandma and us like fools!"
Invoke-CharacterTTS Narrator "He then turned to Lady Wilson and said,"
Invoke-CharacterTTS HaroldWilson "Grandma, this is outrageous! You can't let her go just like that!"
Invoke-CharacterTTS Narrator "Lady Wilson was so angry she was gritting her teeth indignantly. She already felt it was feeble to strike a thirty million dollar deal, but Claire came back half an hour later saying that the contract was worth sixty million dollars… Did the young lady really play her for a fool in front of so many people? Did she really think that, as the head of the family, she could be bullied like this? If she didn't kick the rebellious girl out of her family, how could she control the family in the future? Furrowing furiously, Lady Wilson slapped the table and shouted,"
Invoke-CharacterTTS LadyWilson "Claire Wilson! Go to the HR department immediately to proceed with your resignation!"
Invoke-CharacterTTS Narrator "Claire gaped in extreme bewilderment. Were these people out of their minds? How Hard could it be to just flip the contract open and take a look at it? At this moment, someone shouted abruptly,"
Bystander "Damn! The Official social media account of Emgrand Group has just released a statement! The sixty million dollar contract is real!"