MyNarrator "Decorative lights and illuminants lit up the extravagant Wilson family mansion. Tonight was the 70th birthday banquet of Lady Wilson, the head of the Wilson family. Her grandchildren and their spouses gathered around her to hand her their luxurious gifts."
GeraldWhite "Grandma you are a devout Buddhist, this Buddha statue is carved from aesthetic Hetian jade, it is worth seven hundred thousand dollars…"
Bystander "Grandma, I heard that you love Chinese tea. I looked high and low for the century-old pu'er tea worth half a million dollars to present it to you."
MyNarrator "Looking at the nicely wrapped gifts in front of her, Lady Wilson laughed heartily. The entire ambiance was harmonious and happy. Suddenly, Charlie Wade, Lady Wilson's eldest grandson-in-law, spoke"
CharlieWade "Grandma, could you lend me a million dollars, please? Mrs. Lewis from the welfare home is diagnosed with uremia and I need the money for her treatment…"
MyNarrator "The entire Wilson Family was cast in extreme shock. Everyone stared at Charlie with bewilderment and surprise. This live-in grandson-in-law was overly atrocious and bold! Not only did he not prepare a gift for Lady Wilson on her birthday but he actually had the audacity to ask her for one million dollars! Three years ago, Lord Wilson, who was still alive and well, had come home with Charlie one day and insisted on marrying him to their granddaughter, Claire. At that time Charlie was as poor and miserable as a beggar. After Charlie and Claire were married Lord Wilson died unexpectedly and since then, everyone in the Wilson family tried to kick him out of the family. However, Charlie was always indifferent and nonchalant despite the insults and ridicule. Now he spends his days in the Wilson family quietly as a live-in son-in-law. He was at his wit's end that he had to borrow money from Lady Wilson today. Mrs Lewis, who had taken him in and saved his life, had uremia. She needed at least one million dollars for dialysis and a kidney transplant. He had no other ideas except for asking for lady Wilson's help. He felt that since it was her birthday today, she might be delighted and have some mercy and provide her assistance. Lady Wilson was still laughing gleefully when abruptly her lips curled downward and her eyes furrowed indignantly. She hurled the teacup in her hand to the floor! She looked at Charlie and said"
LadyWilson "Bastard! Are you here to celebrate my birthday or borrow money?"
MyNarrator "Claire hurried forward and said"
ClaireWilson "Grandma, Charlie is not thinking straight, please forgive him."
MyNarrator "She then pulled her husband aside frantically. At this moment, Wendy, Claire's cousin, sneered in disdain."
WendyWilson "Claire, look at the piece of trash you're married to! Gerald is only my fiance and we haven't married yet, but he gifted Grandma the Jade Buddha. Look at your good-for-nothing husband, not only did he come empty-handed but he also has the nerve to ask Grandma for money!"
GeraldWhite "You're right! Charlie, we're both the Grandsons in law of the Wilson family but you're such a disgrace!"
MyNarrator "The man who was talking was Gerald White, Wendy's fiancee who was the son of the wealthy White family of Aurous Hills. Although Gerald was about to marry Wendy, in his eyes, Claire was so much more beautiful and elegant than his fiance. Claire Wilson was the famous goddess of beauty in Aurous Hills. Gerald was very frustrated and irritated when such a beauty got married to a loser."
GeraldWhite "It's best for this useless loser to get out of the Wilson family now!"
WendyWilson "Yes! He is such a disgrace to our family!"
GeraldWhite "Perhaps his intention is not to borrow money but to spoil the joyful ambience of Grandma's birthday instead!"
MyNarrator "Charlie clenched his fists tightly as the entire Wilson family was humiliating and ridiculing him. If it wasn't for the urgency, he would have left this annoying place. However, his father's words echoed in his head. He had taught him to be grateful for the help he received and to return the favor tenfold. Hence, he suppressed the fury and humiliation slowly building within him and said to Lady Wilson."
CharlieWade "Grandma, whoever saves one life saves the world entirely. Please, I beg for your mercy."
MyNarrator "Wendy's brother, Harold Wilson snorted loudly. "
HaroldWilson "Mr. Wade, stop force-feeding chicken soup to Grandma. If you want to rescue someone, you can find a way on your own. Who do you think you are to ask for money from Grandma?"
MyNarrator "The sinister brother and sister had always been prejudiced against Claire, who was superior to them in every aspect. Hence, they would always attack Charlie at any chance they could seize. Claire, who was wearing a slightly awkward expression on her face, started"
ClaireWilson "Grandma, Charlie's father died when he was eight. It was Mrs. Lewis at the welfare home who had brought him up. He is utterly grateful for her graciousness and that is why he wants to return the favor so badly. Could you please help him…"
MyNarrator "Lady Wilson ground with an indignant face."
LadyWilson "You want me to help him? Okay, divorce him now and marry Mr. Jones! If you do as I say, I'll give him one million dollars right away!"
MyNarrator "The Mr. Jones that Lady Wilson was referring to was Wendell Jones, a man who was always pursuing Claire despite her married status. The Jones family was one of the prominent families in the upper social circle in Aurous Hill, which was much more powerful than the Wilson family. Lady Wilson had always wanted to get on their good side. Just then the butler came in and said"
Bystander "Mr. Jones sent a birthday gift to Lady Wilson! It is a Buddha talisman carved from the jadeite stone worth three million dollars!"
MyNarrator "Lady Wilson broke into a large smile and quickly blurted"
LadyWilson "Bring it to me! Let me see!"
MyNarrator "The butler immediately presented the emerald green Buddha talisman which sent waves of exclamation across the living hall. The emerald talisman was crystal clear with its vibrant and sharp colors, without any trace of impurities. It was of the finest Jade quality. Gerald, who had gifted the Buddha statue, gloomed in irritation instantly. He didn't expect Wendell Jones, who had nothing to do with the Wilson family to be so generous and lavish! Lady Wilson caressed the talisman cheerfully and said,"
LadyWilson "Oh, Mr. Jones is so sensible! It would be a sweet dream come true if he were my grandson-in-law!"
MyNarrator "Then, she lifted her gaze at Claire and asked"
LadyWilson "So, how's that? Do you want to consider my terms and conditions?"
MyNarrator "Claire shook her head decidedly"
ClaireWilson "No, Grandma. I will never divorce Charlie."
MyNarrator "A dark stormy Cloud instantly hovered beneath Lady Wilson's eyes. She shouted angrily"
LadyWilson "You ungrateful thing! What good is that loser? Why do you want to waste your time on him? Kick that loser out of my house! He is not allowed at my birthday banquet! I don't want to see his face!"
MyNarrator "Charlie heaved a sigh of dismay and regret. He didn't want to stay with the Wilson family anymore, so he said to Claire"
CharlieWade "I am going to the hospital to visit Mrs. Lewis"
MyNarrator "Claire said quickly"
ClaireWilson "I'll go with you"
MyNarrator "Lady Wilson shouted again"
LadyWilson "If you leave now, you're no longer my granddaughter! You can take your mom, your dad, and that loser and get out of the Wilson family!"
MyNarrator "Claire stared at her grandmother. She did not expect to hear such harsh things coming from her. Charlie interjected"
CharlieWade "You stay here, don't worry about me."
MyNarrator "Before Claire could compose herself from the trance, he turned and left. Harold laughed behind him"
HaroldWilson "Hey, my dear Charlie, if you leave with an empty stomach, will you go on the streets and beg for food? If you do so, you'll tarnish our family name! Here, I have a dollar, you can buy a bun or something to eat!"
MyNarrator "Harold produced a one dollar from his pocket and threw it at Charlie's feet. The entire family's thunderous laughter echoed across the house. Charlie gritted his teeth in annoyance and left the house without looking back. When Charlie arrived at the hospital, he immediately went to the cashier department to try to negotiate an extension of payment for another two days. However, when he approached the nurses, he was informed that overnight, Mrs. Lewis had been transferred to Fairview Hospital, Eastcliff’s top hospital, for treatment. Charlie gasped in shock and quickly asked"
CharlieWade "How much does it cost? I'll find a way to settle it!"
MyNarrator "The nurse said"
Nurse "The bill is three million dollars in total. One million dollars has already been paid, the remaining two million dollars needs to be settled within a week"
CharlieWade "Who covered the one million dollars?"
MyNarrator "The nurse shook his head"
Nurse "I have no idea."
MyNarrator "Charlie frowned in confusion. Just as he turned around, a man of about fifty years of age with gray hair in a black suit was standing behind him. They exchanged glances, and the man bowed before him and said"
StephenThompson "Young Master, we've finally found you! I'm sorry for all the troubles and misery you've suffered for all these years!"
MyNarrator "Charlie furrowed and asked coldly as if he was a completely different person"
CharlieWade "Are you Stephen Thompson?"
MyNarrator "The Man gasped in surprise"
StephenThompson "Young Master, you still remember me"
MyNarrator "Charlie startled slightly and murmured"
CharlieWade "Of course I do! I remember each and everyone of you! You forcibly drove my mom and dad out of Eastcliff along with me and we fled the city. My parents died along the way and I became an orphan. What do you want from me now?"
MyNarrator "Stephen grimaced sorrowfully and said"
StephenThompson "Young Master, Lord Wade was very sad when he learned about your father's death. He never stopped looking for you. Come, let's go home and meet him!"
MyNarrator "Charlie said coldly"
CharlieWade "Just go, I don't want to see him"
MyNarrator "Stephen said"
StephenThompson "Young master, are you still mad at your grandfather?"
CharlieWade "Of course!"
MyNarrator "Charlie said loudly."
CharlieWade "I'll never forgive him in my entire life!"
MyNarrator "Stephen sighed dejectedly"
StephenThompson "Before I came here, the Master did say that you will not forgive him."
CharlieWade "Good! Luckily he still has some sense in him!"
MyNarrator "Stephen continued"
StephenThompson "Lord Wade knows that you've had a hard life for so many years and he's asking me to compensate you if you don't want to go home, he will buy the largest company in Aurous Hill and give it to you. He wants you to take this card, the pin number is your birthday."
MyNarrator "Stephen handed over the premium black card from Citibank."
StephenThompson "Young Master, there are only five of such cards in the country."
MyNarrator "Charlie shook his head sternly"
CharlieWade "No, I don't want it, take it away."
StephenThompson "Young Master, Mrs. Lewis is still two million dollars in debt for her medical bills. If she doesn't pay up, she might be in danger…"
CharlieWade "Are you threatening me? Is this part of your sinister plan?"
MyNarrator "Stephen waved his hands frantically."
StephenThompson "Oh no! We wouldn't dare to do such a thing! Keep the card, then you'll have enough money to pay the bill"
MyNarrator "Charlie asked"
CharlieWade "How much is on this card?"
StephenThompson "Lord Wade said that he deposited some pocket money for you on this card. It's not much, just ten billion dollars!"
