MyNarrator "Chapter 2: I have 10 billion in cash"
MyNarrator "Ten billion dollars?! Charlie was shocked. His eyes wide open, his mouth wide agape. He knew that his grandfather was very wealthy, but back then, he was too young to understand the concept of money. He only knew that the Wade family was one of the wealthiest families in Eastcliff and even the country, but he wasn't sure what his networth was. Right now, he finally knew. If ten billion dollars were just pocket money, it meant that the entire Wade family had a net worth of more than one trillion dollars. Frankly Speaking, at this moment, he was slightly touched and swayed. However, when he thought about his deceased parents and how his grandfather was part of the reasons why they had died, he knew he could never easily forgive him. Sensing his frustration, Stephen quickly said"
StephenThompson "Young Master, you are one of the Wade family members, so the money is yours. Besides, technically speaking, it belongs to your father. The Master said that if you're willing to go home, he will let you inherit the family's one trillion dollar business empire. If you don't want to go home yet, use this money for your living expenses. Oh yes, another piece of news Aurous Hill's Largest and most profitable company, the Emgrand Group with a market value of one hundred billion dollars, had been wholly acquired by the Wade family yesterday. All the equities are now under your name, you can claim your right at the company tomorrow!"
MyNarrator "Charlie listened to him in a daze, completely in disbelief. Wasn't it a little too much investment from the Wade family for his sake? A premium black card with ten billion dollars, Emgrand Group with a net worth of one hundred billion dollars! Although Aurous Hill was a land of talents, the only constant honorable existence was the Emgrand Group. It was the champ of Aurous Hill's business industry! Any prominent and influential family had to bow before the Emgrand Group including those families that humiliated him today: the Wilson family, the White family, and even the Jones family who was still trying to pursue his wife! They were nothing but lowly servants in front of the Emgrand Group! And this magnificent company was his now? Stephen handed him a business card and said"
StephenThompson "Young Master, you might need some time to calm down and think about it, so I'll excuse myself now. This is my card with my number on it, please call me if you need anything!"
MyNarrator "At that, Stephen Turned and Left. Charlie was still in a daze after he left. He didn't know whether he should accept the compensation from the Wade family. However, he recalled the past decade of misery and hardship and the humiliation he had experienced when he married Claire. This was the compensation that the Wade family was giving him for his suffering, so I shouldn't take it? Besides, Miss Lewis urgently needed two million dollars for her treatment. He gritted his teeth as he clutched on the card tightly, then turned back to the cashier department."
CharlieWade "Hi, I would like to settle the bill."
MyNarrator "The card was swiped, the password keyed in, and the transaction was complete. Two million dollars was credited into the hospital's account just like that. Charlie felt like he was still hovering in the clouds. Did he just become a billionaire in the blink of an eye? He went home in a trance. At this moment, the house was fueled with the wrath of fury. Claire and her parents did not live in the Wilson family villa but they stayed in an ordinary house instead. Since Claire married Charlie and after Lord Wilson died, they were kicked out of the Wilson Family villa. His mother-in-law was screaming in great dismay"
ElaineWilson "Charlie Wade, that loser! He's such an embarrassment! If you don't divorce him now, your grandma might kick you out of the Wilson group!"
MyNarrator "Claire said calmly"
ClaireWilson "If she does, I'll just find another job."
ElaineWilson "You…"
MyNarrator "Her mother growled angrily"
ElaineWilson "what's so good about that loser, anyway? Why can't you just divorce him and marry Wendell? If you marry Wendell Jones, our whole family can hold our heads up high!"
MyNarrator "Her father added"
JacobWilson "Your mom's right! If you marry Wendell, our family will immediately become a precious treasure in the family. Your grandma will Cherish you and pamper you every day!"
MyNarrator "Claire uttered"
ClaireWilson "Just stop. I won't divorce Charlie."
JacobWilson "You!"
MyNarrator "Both parents had wanted to keep on persuading Claire when Charlie pushed the door open and walked in. His in-laws gave him a dirty look when they saw him. His mother-in-law snorted in disgust"
ElaineWilson "I thought you'd forgotten the way home, loser!"
MyNarrator "Charlie sighed quietly inside his heart. His mother-in-law had always looked down on him, but what would she do if she were to know that he was now the owner of Emgrand Group and had ten billion dollars in cash? However, this was not the time to reveal his true identity. He had left the Wade family a long time ago, who knew how the family was doing now? What if someone from the family targeted him if he exposed himself? Staying in the dark was the best option for now. Hence, he lowered his head and said humbly"
CharlieWade "Mother, I'm sorry for all the troubles I've caused today."
MyNarrator "His mother-in-law shouted" 
ElaineWilson "Trouble? This is more than trouble, you're putting us at stake! Can't you have the slightest decency and get out of our house?"
MyNarrator "Claire quickly interjected"
ClaireWilson "Mom, how could you say that? Charlie is your son-in-law!"
ElaineWilson "Bullshit" 
MyNarrator "her mother growled"
ElaineWilson "I don't have such a loser as my son-in-law! It's better if he can go as far away as he can!"
MyNarrator "Claire nudged Charlie and said"
ClaireWilson "Hurry, let's go back to the room."
MyNarrator "Charlie nodded gratefully and fled back to the room. They had been married for three years, but they had never consummated the marriage. Claire slept in bed while he slept on the floor at the side. Tonight, Charlie found it hard to fall asleep. What unfolded today was a real shock and consternation and he had yet to digest it. Before going to bed, Claire said,"
ClaireWilson "How is Mrs. Lewis doing? I have about one hundred thousand dollars with me now, you can use it tomorrow."
MyNarrator "Charlie said"
CharlieWade "Thank you, but someone paid her bill and transferred her to Eastcliff for treatment."
ClaireWilson "Really?" 
MyNarrator "Claire exclaimed in awe."
ClaireWilson "Wow! So, Mrs. Lewis will be fine then?"
CharlieWade "Yes,"
MyNarrator 'Charlie said'
CharlieWade "Mrs. Lewis has done good deeds throughout her life and helped so many people. Now, someone is returning her favor."
ClaireWilson "Glad to hear that."
MyNarrator "Claire nodded with a smile." 
ClaireWilson "You can have peace of mind now."
CharlieWade "Yes."
ClaireWilson "I want to sleep now. There's a lot to handle in the company lately, I'm exhausted."
CharlieWade "What's happening in the company?"
ClaireWilson "It's not doing very well lately. Grandma wants to collaborate with Emgrand, but Wilson group is too weak as compared to their scale. They wouldn't even bat an eye at us."
CharlieWade "Oh? Has there not been a collaboration between Wilson group and Emgrand before?"
MyNarrator 'Claire laughed sarcastically.'
ClaireWilson "Of course not! What are we in the eyes of Emgrand? I bet we look like a speck of insignificant dust to them! Even Gerald's family, Wendy's fiance, could barely scratch the tale of Emgrands business empire. This is also why Grandma is eager for them to be married soon so the White family can help our family build some connections with Emgrand"
MyNarrator "Charlie nodded knowingly. The Wilson family had used all the tricks up their sleeves to collaborate with Emgrand Group. However, Lady Wilson never would have thought that he owned Emgrand Group now... Thinking of this, Charlie decided to take over Emgrand Group and lend Claire a hand in her business. The Wilson family did not treat her fairly and they bullied her too much. As her husband, he had the responsibility to help her improve her status in the family. He said from his heart earnestly"
CharlieWade "Claire, your husband is different now! I will not let anyone look down on you again! I will make the entire Wilson family bow down to you!"
