$i = 0
MyNarrator "Chapter 4" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "This is also the first time Charlie had ever met Doris. He Had to admit that Doris was a very stunning and alluring young lady! She was about twenty-seven or twenty-eight years of age with a slender yet curvy body figure, captivating appearance, and a very mature and honorable manner. Sitting down in front of Doris' desk, Charlie started" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "I will not come into the office often, so I would like you to continue looking over the company on my behalf. In addition, please do not disclose my identity to the public." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Doris was aware that Mr. Wade, who was sitting in front of her now, came from the extraordinary Wade family. For a prominent family like theirs, Emgrand Group was nothing but a mediocre business, so it was normal for him not to manage it himself. Hence, she quickly said" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
DorisYoung "Sure. Mr. Wade, just tell me if you need anything, I'll be at your service." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "At this moment, a secretary knocked on the door and said," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
Laird "Miss Young, a man named Gerald White and his fiance are here to see you." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Doris said instantly," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
DorisYoung "I'm seeing a VIP now, let them wait." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Charlie asked," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "Do you know Gerald White?" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
DorisYoung "Mr. White's family is one of our partners and several of their major projects are linked to our company. They had said that they would be here to see me, they have been here several times too." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Charlie uttered in a cold voice," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "From now on,Emgrand Group will no longer have any business dealings with the White family. Halt all ongoing and preparatory projects. If the White family still earns a dime from our company, I don't need you as our vice chairman!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Doris startled in shock, figuring that someone from the White family must have offended Charlie. So, she nodded vigorously and exclaimed," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
DorisYoung "Mr. Wade don't worry, I'll now order my staff to stop all collaboration with the White family!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Charlie nodded satisfyingly And said," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "Tell them that Emgrand Group has no interest in collaborating with lowly garbage, then ask the guards to kick them out." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Outside the office, Gerald and Wendy were waiting anxiously. The White family had always wanted to be the key players in the collaboration with Emgrand Group, so he hoped that he could build a good relationship with Doris Young and thus bring the family closer to the connection. However, the least expected thing happened. Ms. Young's secretary approached them with several guards. Gerald asked in confusion," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "Hi, May I know if Miss Young is available to see us now?" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "The secretary Laird coldly looked at him and said," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
Laird "Sorry our vice chairman said that Emgrand Group has no interest in collaborating with lowly garbage like you. From now on, we will cancel all the projects with your family!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "What did you say?!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Gerald gaped in extreme shock and his jaw almost dropped to the floor. Why did he find the remark so familiar anyway? Oh, right! Charlie Wade said the exact same thing when they were in the parking lot! What Did Doris Young mean by that? Did she really intend to halt all the collaboration with the White family? Gerald felt a surge of blood flooding his head exploding inside. What Happened? Canceled all projects? A large portion of the White family's profits came from working with Emgrand! If Emgrand Group terminated their ties, didn't it mean that the family's net worth would be cut by half? No, he couldn't accept such a cruel fact. He growled loudly," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "I want to see Miss Young! I want to ask her in person!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "The secretary simply glared at him coldly." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
Laird "I'm sorry, Miss Young will not see you and you're not allowed here in the future!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Gerald shouted in great dismay," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "Are you freaking kidding me? We are a long-term business partner of Emgrand, it isn't up to her to terminate our projects just like that! Don't mess with us!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "The secretary ignored his screaming and directed the security guards around her," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
Laird "Kick them out!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "The head of the security team acted immediately. He grabbed Gerald's wrist and twisted it hard behind him. Gerald held in pain and Captain Cooper snorted coldly." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CaptainCooper "Hurry up and get out of here! If you dare make a scene at Emgrand Group, I'll break you in half!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "You're Just a security guard, how dare you raise your voice at me? Do you know who I am?" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Captain Cooper gave him a slap across his face instantly and shouted," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CaptainCooper "What are you in the face of Emgrand Group?" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Gerald felt his face burning from the slap. He was about to burst in fury when his phone suddenly rang. It was his father. When he answered the call, a serious roar echoed from the other end of the line." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
KevinWhite "You bastard! What did you do? Emgrand Group wants to terminate all projects with us! Who on Earth did you offend?" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Gerald whined sorrowfully," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "No, dad, that's not true, I didn't offend anyone. I just came here to see Miss Young, but I haven't even seen her face yet…" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Gerald's father shouted again." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
KevinWhite "The people at Emgrand Group said that they've terminated their collaboration with us because of you, the lowly garbage! It's all because of you that our family is suffering a great loss! Hurry and come back, explain this to your grandfather yourself!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Grabbing the phone in a daze, Gerald and Wendy were forcefully escorted out of Emgrand Groups main entrance.Suddenly, Charlie's face appeared in his mind. He turned to Wendy abruptly and asked," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "Wendy, is this because of your loser cousin-in-law? Does he have anything to do with Emgrand Group?" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
WendyWilson "Huh?"  -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Wendy was obviously taken aback by Gerald's remark. when she pondered the circumstances, it might indeed have something to do with the loser, but he was a loser! Thus, she shook her head and uttered firmly," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
WendyWilson "No, it is absolutely impossible that he has anything to do with Emgrand Group. He's not even qualified to clean their toilets!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "You're right…"  -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Gerald nodded numbly. He hung his head low when he thought about his angry father." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
GeraldWhite "I have to return home right away...." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Very soon, the news of the White family being kicked out of Emgrand Group spread through Aurous Hill like Wildfire. No one knew of the reason, but they were certain that the White family must have offended the Emgrand Group in some way. At this rate, the White family was considered gone. Their net worth has been cut short by more than half. They were originally close to the peak of the social ladder in the city, but after the incident they instantly dropped down several levels and became a second-rate family in terms of social class. Lady Wilson was shaking with anger when she heard the news. She wanted to call off Wendy's engagement with Gerald, but even after the termination, the White family was still more prominent than the Wilson family and she couldn't afford to lose the ties, so she could only bear with it for the moment. Meanwhile, in Doris's office Charlie looked impressed and satisfied after he heard about the process. He highly appreciated her rapid and Stern attitude in it. He said with a satisfied smile," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "Doris, great job, you did well. Starting today, your salary will be doubled." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Doris gasped in astonishment. She stood up and bowed respectfully." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
DorisYoung "Thank you, Mr. Wade!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "Charlie nodded and continued," -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "Also, I want you to make two announcements." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
DorisYoung "Yes, please proceed." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "The first thing is to announce the change of Emgrand Groups ownership and nomination of the new chairman, but don't disclose my identity. Just say that he is one Mr. Wade." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
CharlieWade "The second thing is the announcement of Emgrand Group investing two billion dollars to build a six star hotel in Aurous Hill, and announcing the tender bidding for partners. Construction and interior decorating companies throughout the city are welcome to bid!" -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"
MyNarrator "The main business of Wilson group was interior design and construction. The old lady would dream of hopping on Emgrand's train. Whoever could win the bidding with Emgrand Group would surely become the most sought-after person in the company. Now That he owned Emgrand Group, he could offer his wife some sweet deals." -OutputFile ".\Chapter 4 Audio\TASIL-$i.mp3"