$i=0
MyNarrator 'Chapter 3: Taking over the Emgrand Group' -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "The next morning, after preparing breakfast, Charlie rode his scooter to Emgrand Group's office. He parked his scooter on the side of Emgrand's parking lot. As soon as he locked his scooter, a black Bentley slowly parked in a spot across from him. He looked up inadvertently and saw a young couple getting out of the car. The man was wearing a branded suit, looking very handsome and smart. Meanwhile the lady was dressed up in a flamboyant style. Although somewhat gaudy, she was considered a beauty. As it turned out, the lady was Wendy Wilson, Claire's cousin, and the man was her fiancé, Gerald White. Charlie didn't know why they were here, but he knew that the best way to avoid trouble was to stay away from them. However, the more eager he wanted to hide from them, the higher chances they would see him. Wendy caught sight of him from the corner of her eyes. She yelped loudly," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "Hey, Charlie!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Wendy called out his name in a friendly manner, but Charlie felt goosebumps all over his back. Out of courtesy, he could only stop where he was and wait for them to approach him. He smiled and asked," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "Wendy, hey why are you here?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Wendy chuckled." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "Oh, Gerald is here to see Doris Young, vice-chairman of Emgrand Group! I'm here to keep him company." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Then she turned to look at Gerald with affection and said" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "The White family has a lot of projects with Emgrand Group. Not only would it help the White family but also our Wilson family in the future." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Charlie didn't know that the White was one of Emgrand Group's business partners. After all, he had just taken over the company and he hadn't had time to get through the details. He didn't show anything unusual on his face. Instead, he simply said with a polite smile," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "Mr. White is very talented and magnificent, both of you make a great couple!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Gerald glared at Charlie contemptuously, feeling a surge of anger within him. This loser had been scolded so badly by Lady Wilson yesterday in front of everybody, how was he able to smile like a clown as if nothing had happened today? Why did Claire, such a stunning and wonderful lady marry such a loser? If this loser never existed, he would certainly have pursued Claire with great effort! Who would want to be engaged to Wendy, the girl who paled in comparison in every aspect? Gerald huffed a breath in dismay and asked in a pretentious tone," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "Why are you here?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "I'm here to apply for a job."  -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Charlie said." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "Apply for a job?"  -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Gerald sneered disdainfully." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "You? The loser who can't do anything wants to apply for a job at Emgrand Group? Are you kidding me?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Charlie frowned." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "What has it to do with you?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "The reason why Wendy called Charlie in the first place was to humiliate him. Now that Gerald had started, she immediately mocked," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "Why? Gerald is right, isn't he? In terms of educational background, do you have any achievements or results to show them?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "Trust me, they wouldn't even entertain a loser like you even if you've come to apply for a security job. Know your place, you're better off going to the streets to scavenge for trash, you might earn two or three thousand a month at least!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Then, she hurled a water bottle to Charlie's feet and smirked," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "there you go, pick it up and sell it for money! Don't say that I don't care about you." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Gerald laughed sinisterly. " -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "You are a piece of trash, but we're still relatives after all. I'll have your back. It happens that I know the vice-chairman of Emgrand Group in person, why don't I say a few good words on your behalf and see if she can arrange a toilet cleaning job for you?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Charlie curled his lips and said," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "What kind of job I'm applying for is none of your business, you should mind your one business instead. Emgrand Group is a big company, I believe that they wouldn't want to collaborate with lowly garbage like you." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Gerald's face flushed with anger." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "Who are you calling garbage?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Charlie replied disdainfully, " -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "You, garbage!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Then he turned and walked towards the building, ignoring Gerald's indignant screams behind." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "Damn you! Stop! Stop right there, do you hear me?" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Very soon, Gerald strode quickly and caught up with Charlie at the elevator hall. He wanted to teach Charlie a lesson, to give him at least two slaps on his face to let him know the consequences of offending him, but they were inside Emgrand Groups building now. He was worried that harsh action would tarnish his reputation and infuriate his business partner, so he had no choice but to dismiss the idea. He gritted his teeth and warned," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "I'll let you go today, but you won't be so lucky next time!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Charlie snorted and walked into the elevator. Before the door closed, he said," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
CharlieWade "Gerald White, do you really think you're so powerful? Trust me, you will soon know the price to pay for being so cocky and arrogant!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "You little…" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "Gerald's face turned an ugly shade of red. He wanted to rush into the elevator but Wendy pulled his arms and said," -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
WendyWilson "Gerald, don't take the same elevator as that loser, we might suffocate from his stench." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "He nodded, fully aware that it wasn't wise for him to lay his hands here. Hence, he snorted coldly." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
GeraldWhite "Hah, you're lucky today. I'll teach you a lesson next time!" -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
MyNarrator "In the elevator, Charlie went directly to the top floor where the Chairman's office was located. Stephen had already made all the arrangements for him here at Emgrand. The person in charge of the arrangements was a woman named Doris Young. Doris Young had earned her reputation as a renowned businesswoman in Aurous Hill. Not only was she a Charming lady, but she was also extremely capable. She had been promoted to Vice chairman of Emgrand Group at a young age. She was also among the factors behind the success of the company today. Now that Emgrand Group had been acquired by the Wade family the former chairman had abdicated and Doris stayed back to assist the new chairman. Doris was quite shocked when she saw Charlie. She didn't expect to see such a young and charming man when she had heard about him from Stephen! She quickly composed herself and greeted him respectfully." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"
DorisYoung "Welcome, Mr Wade. Please follow me to my office." -OutputFile ".\Chapter 3 Audio\TASIL-$i.mp3"